export const NEXT_PUBLIC_CLERK_SIGN_IN_URL =
    process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL;

export const NEXT_PUBLIC_CLERK_SIGN_UP_URL =
    process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL;

export const NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL =
    process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL;

export const NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL =
    process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL;

export const NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY =
    process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

export const CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY;

export const NEXT_PUBLIC_TINY_MCE_EDITOR_API_KEY =
    process.env.NEXT_PUBLIC_TINY_MCE_EDITOR_API_KEY;

export const MONGODB_CLUSTER_PUBLIC_URL =
    process.env.MONGODB_CLUSTER_PUBLIC_URL;
